# Generated by Django 3.2.12 on 2023-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('designation_id', models.IntegerField(max_length=255)),
                ('year_of_experience', models.IntegerField(max_length=20)),
            ],
        ),
    ]
